[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2021"
repository = "https://github.com/dfinity/certified-assets"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1.0.56"
assert_cmd = "2"
base64 = "0.22.1"
brotli = "8.0.2"
candid = "0.10.18"
candid_parser = "0.3.0"
flate2 = "1.0"
hex = "0.4.3"
ic-cdk = "0.20.1"
ic-stable-structures = "0.7.2"
itertools = "0.14.0"
mime = "0.3"
mime_guess = "2.0"
num-traits = "0.2.14"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0"
serde_cbor = "0.11.1"
sha2 = "0.11.0"
wit-bindgen = "0.57.1"
tempfile = "3.27.0"
