[package]
name = "plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
brotli = "6.0.0"
candid = { workspace = true }
flate2 = "1.0"
hex = { workspace = true }
mime = "0.3"
mime_guess = "2.0"
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
wit-bindgen = { version = "0.56", features = ["realloc"] }
