[package]
name = "plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
brotli.workspace = true
candid.workspace = true
flate2.workspace = true
hex.workspace = true
mime.workspace = true
mime_guess.workspace = true
serde.workspace = true
serde_bytes.workspace = true
sha2.workspace = true
wit-bindgen = { workspace = true, features = ["realloc"] }
