[package]
name = "e2e"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
assert_cmd.workspace = true
candid.workspace = true
hex.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["blocking"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[build-dependencies]
sha2.workspace = true
