[package]
name = "certified-assets"
version = "0.1.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
certified-assets-lib = { path = "assets" }
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
