name: Check and Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ 1.58.1 ]

    steps:
      - uses: actions/checkout@v2
      - name: rustup
        run: echo ${{ matrix.build }}
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.build }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.build }}-cargo-

      - name: Install and set Rust version based on rust-toolchain.yml
        # uses: actions-rs/toolchain@v1
        # https://github.com/actions-rs/toolchain/pull/209
        uses: zephraph/rust-toolchain@v1

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --tests --benches -- -D clippy::all

      - name: Test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
